version: 0.2
phases:
  install:
    commands:
      - echo "initializing"
  pre_build:
    commands:
      - echo "initializing"
      - - npm install
  build:
    commands:
      - echo "Installing node_modules"
      - npm run build && aws s3 sync build/ s3://hannanbucketti
  post_build:
    commands:
      - echo "Finishing up"